{{- if .Values.master.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "tmate.fullname" . }}
  labels:
    {{- include "tmate.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "tmate.fullname" . }}-master
  minReplicas: {{ .Values.master.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.master.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.master.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.master.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.master.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.master.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}